### ISSUE TITLE
html & css bugs -> Side column for notifications and calendar is not responsive with the feed section in small screens

### ISSUE THREAD

**Issue by salus-sage** [c4sc/arividam#27]
Problem: the mark up created by Django CMS for the content items has a set width and height which is absolute for iframe and Percentage metric for layouting inside feed content blocks. 
The mark up is missing some classes and html wrappers compared to prototype created by designer.

Solution: Change html markup in CMS templates according to the html/css prototype created by designer.

**Comment by arunk** [comment]
@salus-sage can you please check and see if this problem is resolved with the newest templates, and close issue if so

**Comment by salus-sage** [comment]
Solution: left column grids corrected
Issue resolved
